var wikiWorld = [{"c":"Abkhazia","l":"http://en.wikipedia.org/wiki/Abkhazia"},
{"c":"Afghanistan","l":"http://en.wikipedia.org/wiki/Afghanistan"},
{"c":"Akrotiri and Dhekelia","l":"http://en.wikipedia.org/wiki/Akrotiri_and_Dhekelia"},
{"c":"Aland Islands","l":"http://en.wikipedia.org/wiki/%C3%85land_Islands"},
{"c":"Albania","l":"http://en.wikipedia.org/wiki/Albania"},
{"c":"Alderney","l":"http://en.wikipedia.org/wiki/Alderney"},
{"c":"Algeria","l":"http://en.wikipedia.org/wiki/Algeria"},
{"c":"American Samoa","l":"http://en.wikipedia.org/wiki/American_Samoa"},
{"c":"Andorra","l":"http://en.wikipedia.org/wiki/Andorra"},
{"c":"Angola","l":"http://en.wikipedia.org/wiki/Angola"},
{"c":"Anguilla","l":"http://en.wikipedia.org/wiki/Anguilla"},
{"c":"Antigua and Barbuda","l":"http://en.wikipedia.org/wiki/Antigua_and_Barbuda"},
{"c":"Argentina","l":"http://en.wikipedia.org/wiki/Argentina"},
{"c":"Armenia","l":"http://en.wikipedia.org/wiki/Armenia"},
{"c":"Aruba","l":"http://en.wikipedia.org/wiki/Aruba"},
{"c":"Ashmore and Cartier Islands","l":"http://en.wikipedia.org/wiki/Ashmore_and_Cartier_Islands"},
{"c":"Australia","l":"http://en.wikipedia.org/wiki/Australia"},
{"c":"Australian Antarctic Territory","l":"http://en.wikipedia.org/wiki/Australian_Antarctic_Territory"},
{"c":"Austria","l":"http://en.wikipedia.org/wiki/Austria"},
{"c":"Azad Kashmir","l":"http://en.wikipedia.org/wiki/Azad_Kashmir"},
{"c":"Azerbaijan","l":"http://en.wikipedia.org/wiki/Azerbaijan"},
{"c":"Bahrain","l":"http://en.wikipedia.org/wiki/Bahrain"},
{"c":"Bangladesh","l":"http://en.wikipedia.org/wiki/Bangladesh"},
{"c":"Barbados","l":"http://en.wikipedia.org/wiki/Barbados"},
{"c":"Belarus","l":"http://en.wikipedia.org/wiki/Belarus"},
{"c":"Belgium","l":"http://en.wikipedia.org/wiki/Belgium"},
{"c":"Belize","l":"http://en.wikipedia.org/wiki/Belize"},
{"c":"Benin","l":"http://en.wikipedia.org/wiki/Benin"},
{"c":"Bermuda","l":"http://en.wikipedia.org/wiki/Bermuda"},
{"c":"Bhutan","l":"http://en.wikipedia.org/wiki/Bhutan"},
{"c":"Bolivia","l":"http://en.wikipedia.org/wiki/Bolivia"},
{"c":"Bosnia and Herzegovina","l":"http://en.wikipedia.org/wiki/Bosnia_and_Herzegovina"},
{"c":"Botswana","l":"http://en.wikipedia.org/wiki/Botswana"},
{"c":"Brazil","l":"http://en.wikipedia.org/wiki/Brazil"},
{"c":"British Antarctic Territory","l":"http://en.wikipedia.org/wiki/British_Antarctic_Territory"},
{"c":"British Indian Ocean Territory","l":"http://en.wikipedia.org/wiki/British_Indian_Ocean_Territory"},
{"c":"British Virgin Islands","l":"http://en.wikipedia.org/wiki/British_Virgin_Islands"},
{"c":"Brunei","l":"http://en.wikipedia.org/wiki/Brunei"},
{"c":"Bulgaria","l":"http://en.wikipedia.org/wiki/Bulgaria"},
{"c":"Burkina Faso","l":"http://en.wikipedia.org/wiki/Burkina_Faso"},
{"c":"Burma","l":"http://en.wikipedia.org/wiki/Burma"},
{"c":"Burundi","l":"http://en.wikipedia.org/wiki/Burundi"},
{"c":"Cambodia","l":"http://en.wikipedia.org/wiki/Cambodia"},
{"c":"Cameroon","l":"http://en.wikipedia.org/wiki/Cameroon"},
{"c":"Canada","l":"http://en.wikipedia.org/wiki/Canada"},
{"c":"Cape Verde","l":"http://en.wikipedia.org/wiki/Cape_Verde"},
{"c":"Cayman Islands","l":"http://en.wikipedia.org/wiki/Cayman_Islands"},
{"c":"Central African Republic","l":"http://en.wikipedia.org/wiki/Central_African_Republic"},
{"c":"Chad","l":"http://en.wikipedia.org/wiki/Chad"},
{"c":"Chile","l":"http://en.wikipedia.org/wiki/Chile"},
{"c":"China","l":"http://en.wikipedia.org/wiki/China"},
{"c":"Christmas Island","l":"http://en.wikipedia.org/wiki/Christmas_Island"},
{"c":"Clipperton Island","l":"http://en.wikipedia.org/wiki/Clipperton_Island"},
{"c":"Cocos (Keeling) Islands","l":"http://en.wikipedia.org/wiki/Cocos_(Keeling)_Islands"},
{"c":"Collectivity of Saint Martin","l":"http://en.wikipedia.org/wiki/Collectivity_of_Saint_Martin"},
{"c":"Colombia","l":"http://en.wikipedia.org/wiki/Colombia"},
{"c":"Comoros","l":"http://en.wikipedia.org/wiki/Comoros"},
{"c":"Coral Sea Islands Territory","l":"http://en.wikipedia.org/wiki/Coral_Sea_Islands_Territory"},
{"c":"Costa Rica","l":"http://en.wikipedia.org/wiki/Costa_Rica"},
{"c":"Croatia","l":"http://en.wikipedia.org/wiki/Croatia"},
{"c":"Cuba","l":"http://en.wikipedia.org/wiki/Cuba"},
{"c":"Curaçao","l":"http://en.wikipedia.org/wiki/Cura%C3%A7ao"},
{"c":"Cyprus","l":"http://en.wikipedia.org/wiki/Cyprus"},
{"c":"Cyrenaica","l":"http://en.wikipedia.org/wiki/Cyrenaica"},
{"c":"Czech Republic","l":"http://en.wikipedia.org/wiki/Czech_Republic"},
{"c":"Democratic Republic of the Congo","l":"http://en.wikipedia.org/wiki/Democratic_Republic_of_the_Congo"},
{"c":"Denmark","l":"http://en.wikipedia.org/wiki/Denmark"},
{"c":"Djibouti","l":"http://en.wikipedia.org/wiki/Djibouti"},
{"c":"Dominica","l":"http://en.wikipedia.org/wiki/Dominica"},
{"c":"Dominican Republic","l":"http://en.wikipedia.org/wiki/Dominican_Republic"},
{"c":"East Timor","l":"http://en.wikipedia.org/wiki/East_Timor"},
{"c":"Ecuador","l":"http://en.wikipedia.org/wiki/Ecuador"},
{"c":"Egypt","l":"http://en.wikipedia.org/wiki/Egypt"},
{"c":"El Salvador","l":"http://en.wikipedia.org/wiki/El_Salvador"},
{"c":"Equatorial Guinea","l":"http://en.wikipedia.org/wiki/Equatorial_Guinea"},
{"c":"Eritrea","l":"http://en.wikipedia.org/wiki/Eritrea"},
{"c":"Estonia","l":"http://en.wikipedia.org/wiki/Estonia"},
{"c":"Ethiopia","l":"http://en.wikipedia.org/wiki/Ethiopia"},
{"c":"Falkland Islands","l":"http://en.wikipedia.org/wiki/Falkland_Islands"},
{"c":"Faroe Islands","l":"http://en.wikipedia.org/wiki/Faroe_Islands"},
{"c":"Federation of Bosnia and Herzegovina","l":"http://en.wikipedia.org/wiki/Federation_of_Bosnia_and_Herzegovina"},
{"c":"Fiji","l":"http://en.wikipedia.org/wiki/Fiji"},
{"c":"Finland","l":"http://en.wikipedia.org/wiki/Finland"},
{"c":"France","l":"http://en.wikipedia.org/wiki/France"},
{"c":"French Polynesia","l":"http://en.wikipedia.org/wiki/French_Polynesia"},
{"c":"French Southern and Antarctic Lands","l":"http://en.wikipedia.org/wiki/French_Southern_and_Antarctic_Lands"},
{"c":"Gabon","l":"http://en.wikipedia.org/wiki/Gabon"},
{"c":"Georgia (country)","l":"http://en.wikipedia.org/wiki/Georgia_(country)"},
{"c":"Germany","l":"http://en.wikipedia.org/wiki/Germany"},
{"c":"Ghana","l":"http://en.wikipedia.org/wiki/Ghana"},
{"c":"Gibraltar","l":"http://en.wikipedia.org/wiki/Gibraltar"},
{"c":"Gilgit–Baltistan","l":"http://en.wikipedia.org/wiki/Gilgit%E2%80%93Baltistan"},
{"c":"Greece","l":"http://en.wikipedia.org/wiki/Greece"},
{"c":"Greenland","l":"http://en.wikipedia.org/wiki/Greenland"},
{"c":"Grenada","l":"http://en.wikipedia.org/wiki/Grenada"},
{"c":"Guam","l":"http://en.wikipedia.org/wiki/Guam"},
{"c":"Guatemala","l":"http://en.wikipedia.org/wiki/Guatemala"},
{"c":"Guernsey","l":"http://en.wikipedia.org/wiki/Guernsey"},
{"c":"Guinea","l":"http://en.wikipedia.org/wiki/Guinea"},
{"c":"Guinea-Bissau","l":"http://en.wikipedia.org/wiki/Guinea-Bissau"},
{"c":"Guyana","l":"http://en.wikipedia.org/wiki/Guyana"},
{"c":"Haiti","l":"http://en.wikipedia.org/wiki/Haiti"},
{"c":"Heard Island and McDonald Islands","l":"http://en.wikipedia.org/wiki/Heard_Island_and_McDonald_Islands"},
{"c":"Herm","l":"http://en.wikipedia.org/wiki/Herm"},
{"c":"Honduras","l":"http://en.wikipedia.org/wiki/Honduras"},
{"c":"Hong Kong","l":"http://en.wikipedia.org/wiki/Hong_Kong"},
{"c":"Hungary","l":"http://en.wikipedia.org/wiki/Hungary"},
{"c":"Iceland","l":"http://en.wikipedia.org/wiki/Iceland"},
{"c":"India","l":"http://en.wikipedia.org/wiki/India"},
{"c":"Indonesia","l":"http://en.wikipedia.org/wiki/Indonesia"},
{"c":"Iran","l":"http://en.wikipedia.org/wiki/Iran"},
{"c":"Iraq","l":"http://en.wikipedia.org/wiki/Iraq"},
{"c":"Isle of Man","l":"http://en.wikipedia.org/wiki/Isle_of_Man"},
{"c":"Israel","l":"http://en.wikipedia.org/wiki/Israel"},
{"c":"Italy","l":"http://en.wikipedia.org/wiki/Italy"},
{"c":"Ivory Coast","l":"http://en.wikipedia.org/wiki/Ivory_Coast"},
{"c":"Jamaica","l":"http://en.wikipedia.org/wiki/Jamaica"},
{"c":"Japan","l":"http://en.wikipedia.org/wiki/Japan"},
{"c":"Jersey","l":"http://en.wikipedia.org/wiki/Jersey"},
{"c":"Jordan","l":"http://en.wikipedia.org/wiki/Jordan"},
{"c":"Kazakhstan","l":"http://en.wikipedia.org/wiki/Kazakhstan"},
{"c":"Kenya","l":"http://en.wikipedia.org/wiki/Kenya"},
{"c":"Kingdom of the Netherlands","l":"http://en.wikipedia.org/wiki/Kingdom_of_the_Netherlands"},
{"c":"Kiribati","l":"http://en.wikipedia.org/wiki/Kiribati"},
{"c":"Kosovo","l":"http://en.wikipedia.org/wiki/Kosovo"},
{"c":"Kuwait","l":"http://en.wikipedia.org/wiki/Kuwait"},
{"c":"Kyrgyzstan","l":"http://en.wikipedia.org/wiki/Kyrgyzstan"},
{"c":"Laos","l":"http://en.wikipedia.org/wiki/Laos"},
{"c":"Latvia","l":"http://en.wikipedia.org/wiki/Latvia"},
{"c":"Lebanon","l":"http://en.wikipedia.org/wiki/Lebanon"},
{"c":"Lesotho","l":"http://en.wikipedia.org/wiki/Lesotho"},
{"c":"Liberia","l":"http://en.wikipedia.org/wiki/Liberia"},
{"c":"Libya","l":"http://en.wikipedia.org/wiki/Libya"},
{"c":"Liechtenstein","l":"http://en.wikipedia.org/wiki/Liechtenstein"},
{"c":"Lithuania","l":"http://en.wikipedia.org/wiki/Lithuania"},
{"c":"Luxembourg","l":"http://en.wikipedia.org/wiki/Luxembourg"},
{"c":"Macau","l":"http://en.wikipedia.org/wiki/Macau"},
{"c":"Madagascar","l":"http://en.wikipedia.org/wiki/Madagascar"},
{"c":"Malawi","l":"http://en.wikipedia.org/wiki/Malawi"},
{"c":"Malaysia","l":"http://en.wikipedia.org/wiki/Malaysia"},
{"c":"Maldives","l":"http://en.wikipedia.org/wiki/Maldives"},
{"c":"Mali","l":"http://en.wikipedia.org/wiki/Mali"},
{"c":"Malta","l":"http://en.wikipedia.org/wiki/Malta"},
{"c":"Mauritania","l":"http://en.wikipedia.org/wiki/Mauritania"},
{"c":"Mauritius","l":"http://en.wikipedia.org/wiki/Mauritius"},
{"c":"Mexico","l":"http://en.wikipedia.org/wiki/Mexico"},
{"c":"Moldova","l":"http://en.wikipedia.org/wiki/Moldova"},
{"c":"Monaco","l":"http://en.wikipedia.org/wiki/Monaco"},
{"c":"Mongolia","l":"http://en.wikipedia.org/wiki/Mongolia"},
{"c":"Montenegro","l":"http://en.wikipedia.org/wiki/Montenegro"},
{"c":"Montserrat","l":"http://en.wikipedia.org/wiki/Montserrat"},
{"c":"Morocco","l":"http://en.wikipedia.org/wiki/Morocco"},
{"c":"Mozambique","l":"http://en.wikipedia.org/wiki/Mozambique"},
{"c":"Nagorno-Karabakh Republic","l":"http://en.wikipedia.org/wiki/Nagorno-Karabakh_Republic"},
{"c":"Namibia","l":"http://en.wikipedia.org/wiki/Namibia"},
{"c":"Nauru","l":"http://en.wikipedia.org/wiki/Nauru"},
{"c":"Nepal","l":"http://en.wikipedia.org/wiki/Nepal"},
{"c":"Netherlands","l":"http://en.wikipedia.org/wiki/Netherlands"},
{"c":"New Caledonia","l":"http://en.wikipedia.org/wiki/New_Caledonia"},
{"c":"New Zealand","l":"http://en.wikipedia.org/wiki/New_Zealand"},
{"c":"Nicaragua","l":"http://en.wikipedia.org/wiki/Nicaragua"},
{"c":"Niger","l":"http://en.wikipedia.org/wiki/Niger"},
{"c":"Nigeria","l":"http://en.wikipedia.org/wiki/Nigeria"},
{"c":"Norfolk Island","l":"http://en.wikipedia.org/wiki/Norfolk_Island"},
{"c":"North Korea","l":"http://en.wikipedia.org/wiki/North_Korea"},
{"c":"Northern Cyprus","l":"http://en.wikipedia.org/wiki/Northern_Cyprus"},
{"c":"Northern Mariana Islands","l":"http://en.wikipedia.org/wiki/Northern_Mariana_Islands"},
{"c":"Norway","l":"http://en.wikipedia.org/wiki/Norway"},
{"c":"Oman","l":"http://en.wikipedia.org/wiki/Oman"},
{"c":"Pakistan","l":"http://en.wikipedia.org/wiki/Pakistan"},
{"c":"Panama","l":"http://en.wikipedia.org/wiki/Panama"},
{"c":"Papua New Guinea","l":"http://en.wikipedia.org/wiki/Papua_New_Guinea"},
{"c":"Paraguay","l":"http://en.wikipedia.org/wiki/Paraguay"},
{"c":"Peru","l":"http://en.wikipedia.org/wiki/Peru"},
{"c":"Philippines","l":"http://en.wikipedia.org/wiki/Philippines"},
{"c":"Pitcairn Islands","l":"http://en.wikipedia.org/wiki/Pitcairn_Islands"},
{"c":"Poland","l":"http://en.wikipedia.org/wiki/Poland"},
{"c":"Portugal","l":"http://en.wikipedia.org/wiki/Portugal"},
{"c":"Puerto Rico","l":"http://en.wikipedia.org/wiki/Puerto_Rico"},
{"c":"Qatar","l":"http://en.wikipedia.org/wiki/Qatar"},
{"c":"Republic of Ireland","l":"http://en.wikipedia.org/wiki/Republic_of_Ireland"},
{"c":"Republic of Macedonia","l":"http://en.wikipedia.org/wiki/Republic_of_Macedonia"},
{"c":"Republic of the Congo","l":"http://en.wikipedia.org/wiki/Republic_of_the_Congo"},
{"c":"Republika Srpska","l":"http://en.wikipedia.org/wiki/Republika_Srpska"},
{"c":"Romania","l":"http://en.wikipedia.org/wiki/Romania"},
{"c":"Ross Dependency","l":"http://en.wikipedia.org/wiki/Ross_Dependency"},
{"c":"Russia","l":"http://en.wikipedia.org/wiki/Russia"},
{"c":"Rwanda","l":"http://en.wikipedia.org/wiki/Rwanda"},
{"c":"Sahrawi Arab Democratic Republic","l":"http://en.wikipedia.org/wiki/Sahrawi_Arab_Democratic_Republic"},
{"c":"Saint Barthélemy","l":"http://en.wikipedia.org/wiki/Saint_Barth%C3%A9lemy"},
{"c":"Saint Helena, Ascension and Tristan da Cunha","l":"http://en.wikipedia.org/wiki/Saint_Helena,_Ascension_and_Tristan_da_Cunha"},
{"c":"Saint Kitts and Nevis","l":"http://en.wikipedia.org/wiki/Saint_Kitts_and_Nevis"},
{"c":"Saint Lucia","l":"http://en.wikipedia.org/wiki/Saint_Lucia"},
{"c":"Saint Pierre and Miquelon","l":"http://en.wikipedia.org/wiki/Saint_Pierre_and_Miquelon"},
{"c":"Saint Vincent and the Grenadines","l":"http://en.wikipedia.org/wiki/Saint_Vincent_and_the_Grenadines"},
{"c":"Samoa","l":"http://en.wikipedia.org/wiki/Samoa"},
{"c":"San Marino","l":"http://en.wikipedia.org/wiki/San_Marino"},
{"c":"São Tomé and Príncipe","l":"http://en.wikipedia.org/wiki/S%C3%A3o_Tom%C3%A9_and_Pr%C3%ADncipe"},
{"c":"Sark","l":"http://en.wikipedia.org/wiki/Sark"},
{"c":"Saudi Arabia","l":"http://en.wikipedia.org/wiki/Saudi_Arabia"},
{"c":"Senegal","l":"http://en.wikipedia.org/wiki/Senegal"},
{"c":"Serbia","l":"http://en.wikipedia.org/wiki/Serbia"},
{"c":"Seychelles","l":"http://en.wikipedia.org/wiki/Seychelles"},
{"c":"Sierra Leone","l":"http://en.wikipedia.org/wiki/Sierra_Leone"},
{"c":"Singapore","l":"http://en.wikipedia.org/wiki/Singapore"},
{"c":"Sint Maarten","l":"http://en.wikipedia.org/wiki/Sint_Maarten"},
{"c":"Slovakia","l":"http://en.wikipedia.org/wiki/Slovakia"},
{"c":"Slovenia","l":"http://en.wikipedia.org/wiki/Slovenia"},
{"c":"Solomon Islands","l":"http://en.wikipedia.org/wiki/Solomon_Islands"},
{"c":"Somalia","l":"http://en.wikipedia.org/wiki/Somalia"},
{"c":"Somaliland","l":"http://en.wikipedia.org/wiki/Somaliland"},
{"c":"South Africa","l":"http://en.wikipedia.org/wiki/South_Africa"},
{"c":"South Georgia and the South Sandwich Islands","l":"http://en.wikipedia.org/wiki/South_Georgia_and_the_South_Sandwich_Islands"},
{"c":"South Korea","l":"http://en.wikipedia.org/wiki/South_Korea"},
{"c":"South Ossetia","l":"http://en.wikipedia.org/wiki/South_Ossetia"},
{"c":"South Sudan","l":"http://en.wikipedia.org/wiki/South_Sudan"},
{"c":"Spain","l":"http://en.wikipedia.org/wiki/Spain"},
{"c":"Sri Lanka","l":"http://en.wikipedia.org/wiki/Sri_Lanka"},
{"c":"State of Palestine","l":"http://en.wikipedia.org/wiki/State_of_Palestine"},
{"c":"Sudan","l":"http://en.wikipedia.org/wiki/Sudan"},
{"c":"Suriname","l":"http://en.wikipedia.org/wiki/Suriname"},
{"c":"Swaziland","l":"http://en.wikipedia.org/wiki/Swaziland"},
{"c":"Sweden","l":"http://en.wikipedia.org/wiki/Sweden"},
{"c":"Switzerland","l":"http://en.wikipedia.org/wiki/Switzerland"},
{"c":"Syria","l":"http://en.wikipedia.org/wiki/Syria"},
{"c":"Syrian Kurdistan","l":"http://en.wikipedia.org/wiki/Syrian_Kurdistan"},
{"c":"Taiwan","l":"http://en.wikipedia.org/wiki/Taiwan"},
{"c":"Tajikistan","l":"http://en.wikipedia.org/wiki/Tajikistan"},
{"c":"Tanzania","l":"http://en.wikipedia.org/wiki/Tanzania"},
{"c":"Thailand","l":"http://en.wikipedia.org/wiki/Thailand"},
{"c":"The Bahamas","l":"http://en.wikipedia.org/wiki/The_Bahamas"},
{"c":"The Gambia","l":"http://en.wikipedia.org/wiki/The_Gambia"},
{"c":"Togo","l":"http://en.wikipedia.org/wiki/Togo"},
{"c":"Tokelau","l":"http://en.wikipedia.org/wiki/Tokelau"},
{"c":"Tonga","l":"http://en.wikipedia.org/wiki/Tonga"},
{"c":"Transnistria","l":"http://en.wikipedia.org/wiki/Transnistria"},
{"c":"Trinidad and Tobago","l":"http://en.wikipedia.org/wiki/Trinidad_and_Tobago"},
{"c":"Tunisia","l":"http://en.wikipedia.org/wiki/Tunisia"},
{"c":"Turkey","l":"http://en.wikipedia.org/wiki/Turkey"},
{"c":"Turkmenistan","l":"http://en.wikipedia.org/wiki/Turkmenistan"},
{"c":"Turks and Caicos Islands","l":"http://en.wikipedia.org/wiki/Turks_and_Caicos_Islands"},
{"c":"Tuvalu","l":"http://en.wikipedia.org/wiki/Tuvalu"},
{"c":"Uganda","l":"http://en.wikipedia.org/wiki/Uganda"},
{"c":"Ukraine","l":"http://en.wikipedia.org/wiki/Ukraine"},
{"c":"United Arab Emirates","l":"http://en.wikipedia.org/wiki/United_Arab_Emirates"},
{"c":"United Kingdom","l":"http://en.wikipedia.org/wiki/United_Kingdom"},
{"c":"United States","l":"http://en.wikipedia.org/wiki/United_States"},
{"c":"United States Virgin Islands","l":"http://en.wikipedia.org/wiki/United_States_Virgin_Islands"},
{"c":"Uruguay","l":"http://en.wikipedia.org/wiki/Uruguay"},
{"c":"Uzbekistan","l":"http://en.wikipedia.org/wiki/Uzbekistan"},
{"c":"Vanuatu","l":"http://en.wikipedia.org/wiki/Vanuatu"},
{"c":"Vatican City","l":"http://en.wikipedia.org/wiki/Vatican_City"},
{"c":"Venezuela","l":"http://en.wikipedia.org/wiki/Venezuela"},
{"c":"Vietnam","l":"http://en.wikipedia.org/wiki/Vietnam"},
{"c":"Wallis and Futuna","l":"http://en.wikipedia.org/wiki/Wallis_and_Futuna"},
{"c":"Yemen","l":"http://en.wikipedia.org/wiki/Yemen"},
{"c":"Zambia","l":"http://en.wikipedia.org/wiki/Zambia"},
{"c":"Zimbabwe","l":"http://en.wikipedia.org/wiki/Zimbabwe"}];